<?php
/**
 * Custom utility functions for GWT-WordPress.
 *
 * These functions enhance the theme's functionality independently of templates.
 *
 * @package GWT-WordPress
 * @since 26.0.0
 */

/**
 * Add a "Home" link to the fallback menu generated by wp_page_menu().
 *
 * @param array $args Arguments for wp_page_menu().
 * @return array Modified arguments.
 */
function gwt_page_menu_args($args) {
    $args['show_home'] = true;
    return $args;
}
add_filter('wp_page_menu_args', 'gwt_page_menu_args');

/**
 * Add custom classes to the body tag.
 *
 * @param array $classes Existing body classes.
 * @return array Modified body classes.
 */
function gwt_body_classes($classes) {
    // Add a class for multi-author blogs.
    if (is_multi_author()) {
        $classes[] = 'gwt-group-blog';
    }

    return $classes;
}
add_filter('body_class', 'gwt_body_classes');

/**
 * Enhance image navigation by appending an anchor to the attachment link.
 *
 * @param string $url The attachment URL.
 * @param int    $id  The attachment ID.
 * @return string Modified URL.
 */
function gwt_enhanced_image_navigation($url, $id) {
    if (!is_attachment() || !wp_attachment_is_image($id)) {
        return $url;
    }

    $image = get_post($id);
    if (!empty($image->post_parent) && $image->post_parent != $id) {
        $url .= '#main';
    }

    return $url;
}
add_filter('attachment_link', 'gwt_enhanced_image_navigation', 10, 2);

/**
 * Replace the deprecated wp_title filter with add_theme_support('title-tag').
 *
 * Note: This function is no longer needed as of WordPress 4.4.
 */
function gwt_setup_title_tag() {
    add_theme_support('title-tag');
}
add_action('after_setup_theme', 'gwt_setup_title_tag');
